import 'package:flutter/material.dart';

import '../models/beds.dart';

class BedProvider extends ChangeNotifier {
  List<Bed> _bedProviderList = [
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Sunil Rege',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Subhash Bains',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Lalit Kara',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Diya Shenoy',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Chandra Hayre',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Agni Chauhan',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Isha Narayanan',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Surya Oza',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Priti Karpe',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Diya Shenoy',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Ananya Muni',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Pratibha Sibal',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Naisha Guha',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Rachana Tella',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Rahul More',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Ayush Hans',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Manjusha Sani',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Priti Seshadri',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
    Bed(
      hospitalName: 'Apollo Hospital',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 10),
      infoby: 'Asim Ahuja',
      location: 'Jaipur',
      numOfBeds: 10,
      contact: '94256734281',
    ),
  ];

  List<Bed> get bedProviderList {
    return [..._bedProviderList];
  }
}
