import 'package:flutter/material.dart';

import '../models/oxygen.dart';

class OxygenProvider extends ChangeNotifier {
  List<Oxygen> _oxygenProviderList = [
    Oxygen(
      description: 'Gurudas Gas Distribution centre',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Alisha Rana',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 2',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Anik Bansal',
      location: 'Jabalpur',
      numOfCylinders: 5,
      provider: 'Harsh Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Kamakshi Dixit',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Devansh Chandra',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Kani Borah',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Sudhir Som',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Jai Banik',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Vivek Sani',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Anisha Panchal',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Kushal Hegde',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Tushar Parsa',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Narendra Bahri',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Kavi Pandey',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Dhruv Jayaraman',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Sunita Dave',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Prasad Dyal',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Alisha Thakur',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Vinay Luthra',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
    Oxygen(
      description: 'Test 1',
      duration: Duration(hours: 24),
      reportedTime: Duration(hours: 24),
      infoby: 'Pratap Patel',
      location: 'Jaipur',
      numOfCylinders: 5,
      provider: 'Om Prakash',
      contact: '94256734281',
    ),
  ];

  List<Oxygen> get oxygenProviderList {
    return [..._oxygenProviderList];
  }
}
